### ISSUE TITLE
ConcurrentModificationException on calling ThreadLocalSingleWebDriverPool#getDriver

### ISSUE THREAD

**Issue by selenium-course** [barancev/webdriver-factory#14]
On multithread method call ru.stqa.selenium.factory.ThreadLocalSingleWebDriverPool#getDriver got a ConcurrentModificationException.

```
ConcurrentModificationException: null
java.util.ConcurrentModificationException
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at ru.stqa.selenium.factory.ThreadLocalSingleWebDriverPool.dismissDriversInFinishedThreads(ThreadLocalSingleWebDriverPool.java:86)
	at ru.stqa.selenium.factory.ThreadLocalSingleWebDriverPool.getDriver(ThreadLocalSingleWebDriverPool.java:39)

```

**Comment by dozer2** [comment]
Fix in https://github.com/barancev/webdriver-factory/pull/3 on 31 row. 
test for repeat bug

  @Test
  public void testConcurrentModificationExceptionInDismissDriversInFinishedThreadsMethod() {
    List <Thread> threads = new ArrayList<>();
    for (int d = 0; d < 1000; d++) {
      threads.add(new Thread(() -> {factory.getDriver(fakeCapabilities);}));
    }
    for(Thread thread:threads)
    {
        thread.setUncaughtExceptionHandler((t, e) -> {
          if( e instanceof ConcurrentModificationException)
          {
            assertFalse("ConcurrentModificationException" ,true);
          }
        });
        thread.start();
    }
  }

**Comment by barancev** [comment]
Version 4.1 shipped with this issue fixed.
